# NumPy Notes
Numpy is used in storing and manipulating data. 

Check if we got NumPy:

In [2]:
import numpy as np
np.__version__


'1.16.4'

## Data types in python
Python is dynamically typed as apposed to statically typed like c or java.
## A integer is more than just an Integer
In python everything is an object. under the hood everything is based upon a C structure.
![NN1](images/NN1.PNG)

### A single integer in Python 3.4 actually contains four pieces:

ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation

ob_type, which encodes the type of the variable

ob_size, which specifies the size of the following data members

ob_digit, which contains the actual integer value that we expect the Python variable to represent.
### Since python allows for heterozygous lists it adds more complexity


![NN2](images/NN2.PNG)
## Fixed typed Arrays in python
python offeres several efficent storages like the built in array module


In [5]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from python Lists



In [10]:
# integer array:
np.array([1, 4, 2, 5, 3])

## we can change the data type with dtype
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Remember that it all has to be of the same type!
## Numpy data types
![NN3](images/NN3.PNG)

## Manipulating numpy arrays

![NN5](images/NN5.PNG)


## Numpy Array Attributes

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [15]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## Array Indexing (single elements)

Remember that NumPy arrays have fixed types.

In [18]:
print(x1[0])

print(x1[-1])

5
9


In [23]:
print(x2)
x2[0, 0]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


3

## Slicing 
x[start:stop:step]
![NN6](images/NN6.PNG)


![NN7](images/NN7.PNG)

## Reshaping Arrays

reshape()


In [24]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
